config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/usuarios', path_names: {
    sign_in: 'entrar',
    sign_out: 'sair',
    sign_up: 'cadastro',
    password: 'senha',
    edit: 'editar',
    cancel: 'cancelar',
    confirmation: 'confirmacao'
  }, controllers: { registrations: 'auth/registrations' }

  namespace :my, path: '' do
    resources :advertisements, path: 'anuncios', except: [:show]
  end

  root to: 'home#index'
end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
  scope :from_user, -> (user) { where user: user if user.present? }
  scope :most_featured, -> { where(featured: true).sample(12) }

  validates :product, presence: true
  validates :brand, presence: true
  validates :price, presence: true
  validates :description, presence: true

  validates_numericality_of :price, greater_than: 0

  belongs_to :user
  belongs_to :sport
  belongs_to :category

  before_create :set_period

  def expired?
    !DateTime.now.between?(created_at, expires_at)
  end

  private
  def set_period
    self.created_at = DateTime.now
    self.expires_at = self.created_at + 30.days
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/sport.rb
class Sport < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  layout 'application'

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'site'

  def index
    @featured = Advertisement.most_featured
  end
end

app/controllers/my/advertisements_controller.rb
class My::AdvertisementsController < ApplicationController
  layout 'dashboard'
  before_action :authenticate_user!
  before_action :convert_price, only: [:create, :update]

  def new
    @ad = Advertisement.new
  end

  def create
    @ad = Advertisement.new(ad_params)
    @ad.price = @price
    @ad.user = current_user

    if @ad.save
      flash[:saved] = 'Anúncio criado com sucesso.'
      redirect_to my_advertisements_path
    else
      render :new
    end
  end

  def update
    @ad = Advertisement.find(params[:id])
    @ad.price = @price

    if @ad.update(ad_params)
      flash[:success] = 'Anúncio atualizado com sucesso'
      redirect_to my_advertisements_path
    end
  end

  def edit
    @ad = Advertisement.from_user(current_user).find(params[:id])
  end

  def index
    @ads = Advertisement.from_user(current_user)
  end

  private
  def ad_params
    params.require(:advertisement).permit(:product, :price, :brand, :description, :category_id, :sport_id)
  end

  def convert_price
    @price = Monetize.parse(ad_params[:price])
    params['advertisement'].delete('price')
  end
end

app/controllers/profile/profile_controller.rb
class Profile::ProfileController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for :title, page_title.to_s
  end

  def import_font_family(font)
    content_tag :link, nil, href: "http://fonts.googleapis.com/css?family=#{font}", rel: 'stylesheet', type: 'text/css'
  end
end

app/views/home/index.html.erb
<% title 'Tudo para esportes radicais' %>

<% if notice.present? %>
  <%= render partial: 'modals/message', locals: { notice: notice } %>
<% end %>

<header id="header-home">
  <div class="overlay inset-bigger-section">
    <div class="container">
      <nav class="navbar menu-top" id="menu-top">
        <%= link_to 'Quiverbox', root_path, class: 'navbar-brand' %>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= link_to '#', id: 'logged-user', class: 'dropdown-toggle', data: { toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' } do %>
                <%= current_user.name  %>
                <span class="caret"></span>
              <% end %>
              <ul class="dropdown-menu">
                <li><%= link_to 'Meus anúncios', my_advertisements_path %></li>
                <li><%= link_to 'Minha conta', edit_user_registration_path %></li>
                <li><%= link_to 'Sair', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Entrar', new_user_session_path  %></li>
            <li><%= link_to 'Cadastre-se', new_user_registration_path %></li>
          <% end %>
          <li><a href="#" class="btn btn-success">Quero Vender</a></li>
        </ul>
      </nav>

      <div class="row">
        <div class="main-title col-md-12 fadeIn animated">
          <h2>Tudo para esportes radicais</h2>
          <h3>Compre e venda qualquer produto relacionado à esportes radicais</h3>
        </div>
      </div>

      <div class="row col-md-12">
        <div class="search-bar radius">
          <form class="clearfix" action="/">
            <input type="text" class="col-md-10" placeholder="Procure pranchas, skates, equipamentos, camêras e velas">
            <button type="submit" class="btn btn-primary col-md-2">Buscar</button>
          </form>
        </div>
      </div>

    </div>
  </div>
</header>

<section id="featured" class="inset-section">
  <div class="container">
    <div class="section-title">
      <h2>Veja os destaques que separamos pra você</h2>
      <p>Sejam pranchas, rodinhas para skate, quilhas, pipas para kitesurf, não importa. Nós anunciamos os <strong>melhores produtos!</strong></p>
    </div>

    <div class="row">
      <% @featured.each do |advertisement| %>
        <div class="col-md-4">
          <a href="#" class="product">
            <div class="image zooming">
              <%= image_tag 'http://img.olx.com.br/images/38/384513032870795.jpg', alt: advertisement.product %>
              <span>
                <%= number_to_currency(advertisement.price, unit: 'R$ ', separator: ",", delimiter: "") %>
              </span>
            </div>

            <div class="caption clearfix">
              <div class="name pull-left">
                <h3><%= advertisement.product %></h3>
                <p><%= advertisement.brand %></p>
              </div>


            </div>
          </a>
        </div>
      <% end %>
    </div>

    <div class="big-actions">
      <a href="#" class="btn btn-default btn-medium">Explorar</a>
    </div>
  </div>
</section>

<section id="benefits" class="inset-section">
  <div class="container">
    <div class="section-title">
      <h2>Por que anunciar com a gente?</h2>
      <p><strong>nenhum</strong> custo, <strong>maior</strong> facilidade para seus compradores e você atinje pessoas que <strong>realmente estão buscando</strong> esportes radicais</p>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="item radius bounceIn animated">
          <span class="glyphicon glyphicon-piggy-bank pull-left"></span>
          <h4>Nenhum custo para o anunciante</h4>
        </div>
      </div>

      <div class="col-md-4">
        <div class="item radius bounce bounceIn animated">
          <span class="glyphicon glyphicon-flash pull-left"></span>
          <h4>Facilidade e Rapidez</h4>
        </div>
      </div>

      <div class="col-md-4">
        <div class="item radius bounce bounceIn animated">
          <span class="glyphicon glyphicon-bullhorn pull-left"></span>
          <h4>Atinja as pessoas corretas</h4>
        </div>
      </div>
    </div>
  </div>

  <p>Não cobramos nenhum centavo para você anunciar com a gente, mas temos <a href="#">algumas regras</a>.</p>
  <p>Tudo isso para atingirmos o <strong>maior número</strong> de praticantes de esportes radicais!</p>
</section>



<section id="get-started">
  <div class="container">
    <div class="clearfix">
      <div class="pull-left">
        <h3>E aí? Gostou? Entre agora e cadastre-se gratuitamente</h3>
        <p>Tem um monte de gente querendo comprar tudo para esportes radicais. Agiliza!</p>
      </div>

      <%= link_to 'quero vender!', new_user_registration_path, class: 'btn btn-success pull-left' %>
    </div>
  <div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Quiverbox</title>
  <%= import_font_family 'Open+Sans:300,400,600' %>
  <%= import_font_family 'Montserrat:400' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page">

  <header>
    <nav class="navbar navbar-white nav-bigger navbar-static-top">
      <div class="container">
        <%= link_to 'Quiverbox', root_path, class: 'navbar-brand' %>
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" />
          </div>
        </form>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><a href="#">Ajuda</a></li>
            <li><a href="#">Minhas vendas</a></li>
          <% else %>
            <li><%= link_to 'Cadastre-se', new_user_registration_path %></li>
          <% end %>
          <li><a href="#" class="btn btn-success">Anuncie Grátis</a></li>
        </ul>
      </div>
    </nav>
  </header>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Quiverbox</title>
  <meta charset="UTF-8">
  <%= import_font_family 'Open+Sans:300,400,600' %>
  <%= import_font_family 'Montserrat:400' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="dashboard">

  <header>
    <nav class="navbar navbar-white nav-bigger navbar-static-top">
      <div class="container">
        <%= link_to 'Quiverbox', root_path, class: 'navbar-brand' %>
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" />
          </div>
        </form>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li>
              <a href="#">
                <span class="glyphicon glyphicon-question-sign"></span>
                Ajuda</a>

            </li>
            <li><a href="#"><%= current_user.name %></a></li>
          <% else %>
            <li><%= link_to 'Cadastre-se', new_user_registration_path %></li>
          <% end %>
          <li>
            <%= link_to new_my_advertisement_path, class: 'btn btn-success' do %>
              QUERO VENDER
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="menu-user radius">
          <div class="image">
            <%= image_tag 'placeholders/user-placeholder-large.png', class: 'img-circle' %>

            <% if user_signed_in? %>
              <h4><%= current_user.name %></h4>
            <% end %>
          </div>

          <ul class="nav nav-pills nav-stacked">
            <li>
              <%= link_to my_advertisements_path do %>
                <span class="glyphicon glyphicon-usd"></span>
                Meus anúncios
              <% end %>
            </li>

            <li>
              <%= link_to '#' do %>
                <span class="glyphicon glyphicon-inbox"></span>
                Mensagens
                <span class="label label-danger pull-right">2</span>
              <% end %>
            </li>

            <li>
              <%= link_to edit_user_registration_path do %>
                <span class="glyphicon glyphicon-user"></span>
                Minha conta
              <% end %>
            </li>
          </ul>
        </div>

        <div class="important-ad">
          <%= link_to new_my_advertisement_path, class: 'btn btn-success btn-bigger' do %>
            <span class="glyphicon glyphicon-usd"></span>
            Anuncie Grátis
          <% end %>
        </div>
      </div>

      <div class="col-md-9">
        <% if notice.present? %>
          <div class="alert alert-success">
            <p><strong>Sucesso!</strong> <%= notice %></p>
          </div>
        <% end %>

        <div class="content radius">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/navbars/_navbar_white.html.erb
<nav class="navbar navbar-white nav-bigger <%= type %>" style="display: none;" id="navbar-fixed">
  <div class="container">
    <%= link_to 'Quiverbox', root_path, class: 'navbar-brand' %>
    <form class="navbar-form navbar-left">
      <div class="form-group">
        <input type="text" class="form-control" />
      </div>
    </form>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><a href="#">Como Funciona</a></li>
        <li><a href="#"><%= current_user.name %></a></li>
      <% else %>
        <li><%= link_to 'Cadastre-se', new_user_registration_path %></li>
      <% end %>
      <li>
        <%= link_to new_my_advertisement_path, class: 'btn btn-success' do %>
          QUERO VENDER
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Quiverbox</title>
  <%= import_font_family 'Open+Sans:300,400,600' %>
  <%= import_font_family 'Montserrat:400' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="home">
  <%= render partial: 'layouts/navbars/navbar_white', locals: { type: 'navbar-fixed-top' } %>

  <%= yield %>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="menu">
            <h4>Quiverbox</h4>
            <ul>
              <li><a href="#">Como Funciona</a></li>
              <li><a href="#">Termos de Uso</a></li>
              <li><a href="#">Política de Privacidade</a></li>
              <li><a href="#">Contato</a></li>
            </ul>
          </div>
        </div>

        <div class="col-md-3">
          <div class="menu">
            <h4>Quero Anunicar</h4>
            <ul>
              <li><a href="#">Preços</a></li>
              <li><a href="#">Política de Entrega</a></li>
              <li><a href="#">Política de Venda</a></li>
              <li><a href="#">Suporte</a></li>
            </ul>
          </div>
        </div>

        <div class="col-md-3">
          <div class="menu">
            <h4>Marcas favoritas</h4>
            <ul>
              <li><a href="#">Billabong</a></li>
              <li><a href="#">GT Boards</a></li>
              <li><a href="#">Element</a></li>
              <li><a href="#">Flora Surfboards</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>
</body>
</html>

app/views/modals/_message.html.erb
<div class="modal fade in" id="modal-message">
  <div class="modal-dialog">
    <div class="modal-content radius">
      <div class="modal-header clearfix">
        <h4>Verifique sua caixa de email</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        <p><%= notice %></p>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-danger btn-medium" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/modals/_new_advertisement.html.erb
<div class="modal fade in" id="modal-message">
  <div class="modal-dialog">
    <div class="modal-content radius">
      <div class="modal-header clearfix">
        <h4>Parabéns, seu anúncio foi criado!</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body important-message">
        <p>E aí, <%= current_user.name %>, beleza?</p>

        <p>Seu anúncio foi criado com sucesso, agora ele vai ser revisado pela nossa equipe e em até <strong>10 minutos</strong>
          ele já estará disponível no Quiverbox.</p>

          <p>Caso haja algum problema que não podemos resolver, entraremos em contato.</p>

        <p>Aloha!</p>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-danger btn-medium" data-dismiss="modal">Fechar</button>
      </div>
    </div>
  </div>
</div>

app/views/my/advertisements/edit.html.erb
<% title "Editar anúncio - #{@ad.product}" %>

<%= form_for [:my, @ad], html: { class: 'form-horizontal' } do |f| %>
  <div class="form-title clearfix">
    <h2 class="pull-left">Imagens do seu anúncio</h2>
    <p class="pull-right">Capricha aí, você pode ter até <strong>85%</strong> mais de chance de vender. <a class=" important-info" href="#">Política de imagens</a></p>
  </div>

  <% unless @ad.errors.empty? %>
    <div class="alert alert-warning">
      <ul>
        <% @ad.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fieldset">
    <div class="row">
      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="http://placehold.it/164x164">
        </a>
      </div>

      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="http://placehold.it/164x164">
        </a>
      </div>

      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="http://placehold.it/164x164">
        </a>
      </div>

      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="http://placehold.it/164x164">
        </a>
      </div>
    </div>
  </div>

  <div class="form-title clearfix">
    <h2 class="pull-left">Dados do seu produto</h2>
    <a class="pull-right important-info" href="#">Veja aqui as regras para os anúncios</a>
  </div>
  <div class="fieldset">
    <div class="form-group">
      <%= f.label :product, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :product, autofocus: true, class: 'form-control', placeholder: 'Nome do seu produto' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :price, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :price, value: number_to_currency(@ad.price, unit: 'R$ ', separator: ",", delimiter: ""), class: 'form-control', placeholder: 'Marca do seu produto', rel: 'currency' %>
        <p class="info-file">Valor em BRL (R$). Ex.: R$ 23,99</p>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :brand, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :brand, class: 'form-control', placeholder: 'Marca do seu produto' %>
        <p class="info-field">Sugestões: Hurley, Oakley, Rip Curl, GoPro, etc..</p>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :category, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <%= f.select :category_id, options_from_collection_for_select(Category.all, 'id', 'name'), { include_blank: 'Selecione a categoria' }, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :sport, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <%= f.select :sport_id, options_from_collection_for_select(Sport.all, 'id', 'name'), { include_blank: 'Selecione o esporte' }, class: 'form-control'  %>
        <p class="info-field">Isso melhorará o rankeamento do seu produto, <a href="#">veja por quê</a>.</p>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <div class="description-box">
          <%= f.text_area :description, class: 'form-control', rows: 10  %>
          <div id="md-preview" style="display: none;">

          </div>
        </div>
        <p class="info-field">
          <span id="chars-counter">140</span> caracteres.
          <button id="btn-preview" class="btn btn-link">Veja como vai ficar</button></p>
      </div>
    </div>

    <div class="actions">
      <%= f.submit 'Criar anúncio', class: 'btn btn-primary btn-medium', name: '' %>
    </div>
  </div>
<% end %>

app/views/my/advertisements/index.html.erb
<% title 'Meus anúncios' %>

<% if flash[:saved].present? %>
  <%= render partial: 'modals/new_advertisement', locals: { notice: notice } %>
<% end %>

<div class="form-title">
  <h2>Anúncios Ativos</h2>
</div>

<div class="fieldset">
  <% if @ads.empty? %>
    <div class="no-results">
      <h4>Você ainda não tem nenhum anúncio</h4>

      <%= link_to 'Comece agora!', new_my_advertisement_path, class: 'btn btn-primary btn-medium' %>
    </div>
  <% else %>
  <table class="table" id="table_ads">
    <thead>
      <tr>
        <th width="70%">Produto</th>
        <th width="20%">Expira em</th>
        <th width="10%"></th>
      </tr>
    </thead>

    <tbody>
      <% @ads.each do |ad| %>
        <tr>
          <td>
            <span class="label label-info">aguardando aprovação</span>
            <%= link_to edit_my_advertisement_path(ad) do %>
              <%= ad.product %>
            <% end %>
          </td>
          <td><%= distance_of_time_in_words(DateTime.now, ad.expires_at) %></td>
          <td>
            <%= button_to '#', class: 'btn btn-danger' do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>

app/views/my/advertisements/new.html.erb
<% title 'Novo anúncio' %>

<%= form_for [:my, @ad], html: { class: 'form-horizontal' } do |f| %>
  <div class="form-title clearfix">
    <h2 class="pull-left">Imagens do seu anúncio</h2>
    <p class="pull-right">Capricha aí, você pode ter até <strong>85%</strong> mais de chance de vender. <a class=" important-info" href="#">Política de imagens</a></p>
  </div>

  <% unless @ad.errors.empty? %>
    <div class="alert alert-warning">
      <ul>
        <% @ad.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fieldset">
    <div class="row">
      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="http://placehold.it/164x164">
        </a>
      </div>

      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="http://placehold.it/164x164">
        </a>
      </div>

      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="http://placehold.it/164x164">
        </a>
      </div>

      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="http://placehold.it/164x164">
        </a>
      </div>
    </div>
  </div>

  <div class="form-title clearfix">
    <h2 class="pull-left">Dados do seu produto</h2>
    <a class="pull-right important-info" href="#">Veja aqui as regras para os anúncios</a>
  </div>
  <div class="fieldset">
    <div class="form-group">
      <%= f.label :product, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :product, autofocus: true, class: 'form-control', placeholder: 'Nome do seu produto' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :price, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :price, class: 'form-control', placeholder: 'Marca do seu produto', rel: 'currency' %>
        <p class="info-file">Valor em BRL (R$). Ex.: R$ 23,99</p>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :brand, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <%= f.text_field :brand, class: 'form-control', placeholder: 'Marca do seu produto' %>
        <p class="info-field">Sugestões: Hurley, Oakley, Rip Curl, GoPro, etc..</p>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :category, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <%= f.select :category_id, options_from_collection_for_select(Category.all, 'id', 'name'), { include_blank: 'Selecione a categoria' }, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :sport, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <%= f.select :sport_id, options_from_collection_for_select(Sport.all, 'id', 'name'), { include_blank: 'Selecione o esporte' }, class: 'form-control'  %>
        <p class="info-field">Isso melhorará o rankeamento do seu produto, <a href="#">veja por quê</a>.</p>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class: 'col-sm-3 control-label' %>
      <div class="col-sm-8">
        <div class="description-box">
          <%= f.text_area :description, class: 'form-control', rows: 10 %>
          <div id="md-preview" style="display: none;">

          </div>
        </div>
        <p class="info-field">
          <span id="chars-counter">140</span> caracteres.
          <button id="btn-preview" class="btn btn-link">Veja como vai ficar</button></p>
      </div>
    </div>

    <div class="actions">
      <%= f.submit 'Criar anúncio', class: 'btn btn-primary btn-medium', name: '' %>
    </div>
  </div>
<% end %>